id: PEAA36AF6
initial_creation_type: input
source_metadata:
  title: Long-Life Prayers
  language: fr
  description: 'A selection of prayers for longevity (zhabs brtan), first more general
    ones, then those for specific individuals (arranged alphabetically by subject):'
  volume:
    3557db21f9c44fca96547ba10391bd1b:
      title: 'Youthfulness Gained in Vajra-like Immortality: Verses of Truth for the
        Long Life of the Perfect Masters'
      parent: General
    3c1715c6bfe84082bfe4d39d4a91ca50:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: General
    f78ddbbb7f7d438a9e149a6f67054bb0:
      title: General Long-Life Prayer
      parent: General
    3403124d8cbe4c0db7fda56bad41abda:
      title: 'The Melodious Song of Immortality: A Prayer for Long Life'
      parent: General
    0c95c2dca0384f698884b51b67236a89:
      title: Prayer for the Long Life of Alak Zenkar Rinpoche, the Incarnation of
        Do Khyentsé Yeshé Dorjé
      parent: Alak Zenkar Rinpoche
    928ffbd318e84269af30c43a31337e4a:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Alak Zenkar Rinpoche
    6e6b5dc531244de899ddc36a50eca053:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Chökyi Nyima Rinpoche
    0e817382655543f6a26d71d57701e5e6:
      title: 'The Great Treasure of a Hundred Blessings: A Prayer for the Long Life
        of Ḍākinī Muntso Rinpoche'
      parent: Ḍākinī Muntso Rinpoche
    3a4ed0d1fcf54a649de1db8d48e1298a:
      title: Aspiration for the Long Life of Dezhung Rinpoche (Jampa Kunga Tenpé Nyima)
      parent: Dezhung Rinpoche
    b3c460853f1849d1a5a7839c9b9a9ec6:
      title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin
        Jigme Lhundrup
      parent: Dilgo Khyentse Yangsi Rinpoche
    304bf86ff46a44baa2a870822852c54a:
      title: Prayer for the Long Life Dodrupchen Rinpoche
      parent: Dodrupchen Rinpoche
    3abe9d675fc84633a0762cf66575187c:
      title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great
        Tertön Dudjom Jigdral Yeshe Dorje'
      parent: Dudjom Rinpoche
    a7b0dc7f56374311b48fc502ae761a06:
      title: Prayer for the Long Life of Dzogchen Rinpoche
      parent: Dzogchen Rinpoche
    3aea4777ec9845fe94737c8816ba5deb:
      title: Prayer for the Long Life of Dzongsar Jamyang Khyentse Rinpoche
      parent: Dzongsar Khyentse Rinpoche
    c6b5bc5488694905b4425ab34020505c:
      title: 'True Words to Accomplish Immortality: A Longevity Prayer to the Tulku
        of Jamyang Khyentse, Thupten Chökyi Gyatso'
      parent: Dzongsar Khyentse Rinpoche
    cdee70b06a7a4621914065b7e2d20319:
      title: A Supplication for the Longevity of the Peerless and Sublime Tulku, Dzongsar
        Khyentse, Thupten Chökyi Gyatso
      parent: Dzongsar Khyentse Rinpoche
    137ccf8006a9476a80cab5156db4db87:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Fourteenth Dalai Lama
    82d29294b03546d4bef1e46fbc145338:
      title: 'The Magical Wish-Fulfilling Tree: A Prayer for the Long Life of His
        Holiness the Dalai Lama'
      parent: Fourteenth Dalai Lama
    9df01d22f82b4ec7af8ae191b526b794:
      title: 'The Melody of The Nectar of Immortality: A Prayer for the Long Life
        of His Holiness the Fourteenth Dalai Lama, Supreme Victor and Omniscient One
        by Jamyang Khyentse Chökyi Lodrö'
      parent: Fourteenth Dalai Lama
    15dd01da270f4601b52b18e7842583ae:
      title: 'The Music of Immortality: A Prayer for the Long Life of His Holiness
        the Dalai Lama'
      parent: Fourteenth Dalai Lama
    ae7a85d4cd52426bae3f5eb3cec9dad0:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Fourteenth Dalai Lama
    741b22deeaf944e69c65746bf81aa70d:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
      parent: Jamyang Khyentse Chökyi Lodrö
    c8c50664b4bb4003abc59031689a3517:
      title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö and Khandro
        Tsering Chödrön
      parent: Jamyang Khyentse Chökyi Lodrö
    280c58bd05d346da960bd7939d87e6c9:
      title: 'Sweet Song of Enduring Deathlessness: A Prayer for the Long Life of
        Jamyang Khyentse Chökyi Lodrö'
      parent: Jamyang Khyentse Chökyi Lodrö
    b60daaaa541641568601940503fd2f39:
      title: Long-Life Prayer Presented to the Incarnation of Shukseb Jetsünma
      parent: Jetsün Lochen Incarnation
    eee56bdb50f14a908ecd42225e4ca839:
      title: Prayer for the Long Life of Khandro Tāre Lhamo
      parent: Khandro Tāre Lhamo
    4723cef8f93747b1a4676d5f1360208b:
      title: Prayer for the Long Life of Khandro Tsering Chödrön
      parent: Khandro Tsering Chödrön
    924e23823807485d82ca307bed257303:
      title: Prayer for the Long Life of Khyenrab Chökyi Özer
      parent: Khyenrab Chökyi Özer
    6d9058ec51e449f9b17e7b69c26a66b4:
      title: 'The Flower of Auspiciousness: A Prayer for the Long Life of Khenpo Khyenrab
        Chökyi Özer, Masterful Expositor of Scripture and Reasoning'
      parent: Khyenrab Chökyi Özer
    88b909406dd041c787bcdc8b777f6b40:
      title: 'The Sweet Melody to Accomplish Words of Truth: A Prayer for the Long
        Life of the Dharma-Expounding Guide Khenchen Khyenrab Chökyi Özer'
      parent: Khyenrab Chökyi Özer
    90a6d55c1e1f4c9ca566e3b963290859:
      title: Prayer for the Long Life of Lochen Ngawang Chöpal
      parent: Lochen Dharmaśrī
    35bccc9722b046d3b92fe4e8fd150da3:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Lodi Gyari Rinpoche
    704650db97234af7812040181d04b0cd:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Mayum Tsering Wangmo
    ca1f7b071f9d4b76aaf11608c5bb968d:
      title: 'The Drum of Deathlessness: A Prayer for the Long Life of Minling Chung
        Rinpoche'
      parent: Minling Chung Rinpoche
    980ffd3d8ea341bd8794de96dce4dd53:
      title: Prayer for the Long Life of Namkhai Norbu Rinpoche
      parent: Namkhai Norbu Rinpoche
    628c14aeea324d439c68c5a1b4b8fd27:
      title: 'The Vajra Sitar of Immortality: A Prayer for the Long Life of the Fourth
        Incarnation of Terchen Chokgyur Lingpa'
      parent: Neten Chokling Rinpoche
    834a54edc17542cdb92736f51a6c34f3:
      title: Prayer for the Long Life of Orgyen Tobgyal Rinpoche
      parent: Orgyen Tobgyal Rinpoche
    82712186bb584bfeaafabe4f2aa7f9c1:
      title: Long Life Prayer for Patrick Gaffney (Yeshé Wangyal)
      parent: Patrick Gaffney
    f101344e96284b53bac5585542edf844:
      title: Prayer for the Long Life of Pema Norbu, Lord of Siddhas
      parent: Penor Rinpoche
    1b410416d36041ffa39891ad40f9cb4f:
      title: Prayer for the Long Life of Pewar Rinpoche
      parent: Pewar Rinpoche
    24bf08163e1e4ee581fc5b91963ab7a5:
      title: Prayer for the Long Life of the Glorious Sakyapa Father and Son
      parent: Sakya Dagchen and Son
    9b61c8c1970f418eb03f32643f86a48a:
      title: A Prayer for the Long Life of Ngawang Kunga Tekchen Palbar Trinlé Wangi
        Gyalpo, the Lord of Refuge and Precious Holder of the Throne of the Drolma
        Palace at Glorious Sakya
      parent: Sakya Trichen
    65e9941cc9834de2b20e625cf9ea7182:
      title: Prayer for the Long Life of Kyabgön Sakya Trichen
      parent: Sakya Trichen
    549d2d5eea1443e3b4e99f5beebf1ad3:
      title: Prayer for the Long Life of Shechen Rabjam Rinpoche
      parent: Shechen Rabjam Rinpoche
    2ef16e9b1597467a9945b9103e2199b2:
      title: The Excellent Stream of Nectar of Immortality
      parent: Sogyal Rinpoche
    cf4a1cdf961d41ffbeb1347e2c761dff:
      title: Gentle Rain of the Nectar of Immortality
      parent: Sogyal Rinpoche
    e6bfe7d50aeb483ca2a9af32342c5025:
      title: Prayer for the Long Life of Sogyal Rinpoche—chimé kunnyé
      parent: Sogyal Rinpoche
    e00a5ba610d04a54aee68cbdfd91fdb6:
      title: Prayer for the Long Life of Sogyal Rinpoche—sönam jewé
      parent: Sogyal Rinpoche
    571e752a22894a74bbca4bfa661408c8:
      title: The Attainment of Immortality
      parent: Sogyal Rinpoche
    a6c0fa2bf41e4cbeb927bcfbdb5d2ddb:
      title: Prayer for the Long Life of Soktsé Rinpoche
      parent: Soktsé Rinpoche
    7ed163a74bea457bb20b735194526563:
      title: 'Padma’s Melodious Song: A Prayer for the Long Life of the Fourth in
        the Succession of Lotus-Tongued Jamchen Tai Situ Incarnations'
      parent: Tai Situ Rinpoche
    aa98edc1ed33400e93c811f8dc8a861b:
      title: Prayer for the Long Life of Taklung Tsetrul Rinpoche
      parent: Taklung Tsetrul Rinpoche
    5bdc3f935d184e069d1ef07cbc2e05b5:
      title: 'The Sound of the Auspicious Conch: A Prayer for the Long Life of the
        All-Knowing Paṇchen Rinpoche of Tsang'
      parent: Tenth Paṇchen Lama
    d0b7a885a3f14c9890039651da586f37:
      title: 'The Sweet Song of Māra''s Defeat: A Prayer for the Long Life of the
        Great Tertön and Vidyādhara Lerab Lingpa'
      parent: Tertön Sogyal Lerab Lingpa
    73b534a1f92342da99c47e907a40a501:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Trulshik Rinpoche
    afab7c9bc3784a6da2d7476984a0c7d7:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Trulshik Rinpoche
    0b269f09e1c6499d99739b474733425b:
      title: Prayer for the Long Life of Tulku Thondup Rinpoche
      parent: Tulku Thondup Rinpoche
created_at: '2022-03-01T04:19:58.006993'
last_modified_at: '2022-03-01T04:19:58.006999'
